### ISSUE TITLE
pageのupdateを実装

### ISSUE THREAD

**Issue by okisidentarisu** [jphacks/KB_2312#2]
`/model/mutation.rs`について

### create_pageを基にupdate_pageを作成する

以下、参考
- titleを変更できるように作られている（その実装はまだ作ってないけど···）ため、2回sqlを発行する仕様にした方がいいかもです。
- updateするとそのpageが存在しない。というのを考慮してreturningでidを返すようにしてください。
- updateできない = そのpageが存在しない(if id.is_none())なのでNoneを返すようにして下さい。(return Ok(None;))
- 上記ができるとtilte更新→body更新という感じに出来ると思います。

なお、`UpdatePageInput`も一旦未定義で開発を進めます。

**Comment by darallium** [comment]
> titleを変更できるように作られている（その実装はまだ作ってないけど···）ため、2回sqlを発行する仕様にした方がいいかもです。
sub問い合わせで存在チェックしながら行進ではない理由は何ですか?

**Comment by darallium** [comment]
> titleを変更できるように作られている（その実装はまだ作ってないけど···）ため、2回sqlを発行する仕様にした方がいいかもです。

sub queryで

**Comment by darallium** [comment]
> titleを変更できるように作られている（その実装はまだ作ってないけど···）ため、2回sqlを発行する仕様にした方がいいかもです。

sub queryで存在チェックをしながら代入しない理由は何ですか?

**Comment by darallium** [comment]
> titleを変更できるように作られている（その実装はまだ作ってないけど···）ため、2回sqlを発行する仕様にした方がいいかもです。

sub queryで存在チェックをしながら代入したらSQLのクエリを飛ばす回数を減らせると思うんですがどうですか？

**Comment by darallium** [comment]
更新時にはauthorは更新しますか？
